name: Jur Job Scanner

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:

  scan:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - run: python scanner.py
        env:
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
